# Generated by Django 3.1.4 on 2021-01-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20210119_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='docter',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
