# Generated by Django 3.1.4 on 2021-01-17 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Docter',
            new_name='Docter1',
        ),
        migrations.RenameModel(
            old_name='Patient',
            new_name='Patient2',
        ),
    ]
